version: "3"

services:
  wp:
    build:
      context: ./wordpress
    ports:
      - "8080:80"
    depends_on:
      - db
    volumes:
      - ./wordpress/wp-content:/var/www/html/wp-content
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress

  db:
    image: mysql:latest
    restart: always
    volumes:
      - ./.db/data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: foobar123
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress

